from jutge import read

#GAGTTTTATCGCTTCCATGACGCAGAAGTTAACACTTTCGGATATTTCTGATGAGTCGAAAAATTATCTTGATAAAGCAGGAATTACTACTGCTTGTTTACGAATTAAATCGAAGTGGACTGCTGGCGGAAAATGAGAAAATTCGACCTATCCTTGCGCAGCTCGAGAAGCTCTTACTTTGCGACCTTTCGCCATCAACTAACGATTCTGTCAAAAACTGACGCGTTGGATGAGGAGAAGTGGCTTAATATGCTTGGCACGTTCGTCAAGGACTGGTTTAGATATGAGTCACATTTTGTTCATGGTAGAGATTCTCTTGTTGACATTTTAAAAGAGCGTGGATTACTATCTGAGTCCGATGCTGTTCAACCACTAATAGGTAAGAAATCATGAGTCAAGT

seq = read(str)

prep = ""

for x in range(len(seq)-2):
	
	if  seq[x]=="A" and seq[x+1]=="T" and seq[x+2]=="G":
		prep = seq[x:len(seq)]

		l = []
		
		for i in range(0, len(prep), 3):
			l.append(prep[i:i+3])
		
		res = ""
		
		for k in l:
			if k=="TAA" or k=="TAG" or k=="TGA":
				
				res+=k
				print(res)
				break
			
			else:
				res+=k
